# Generated by Django 3.2.5 on 2021-07-03 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.CharField(max_length=30000)),
                ('created_date', models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 3, 3, 27, 5, 76300, tzinfo=utc))),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
