# Generated by Django 3.2.5 on 2021-08-15 07:44

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daytoday', '0009_daily_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='content',
            field=ckeditor.fields.RichTextField(validators=[django.core.validators.MinLengthValidator(30000)]),
        ),
    ]
