# Generated by Django 3.2.5 on 2021-08-28 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daytoday', '0015_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 28)),
        ),
    ]
